import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'id' | 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

// File terjemahan
const translations = {
  id: {
    // Header
    'nav.home': 'Beranda',
    'nav.profile': 'Profil Prodi',
    'nav.curriculum': 'Kurikulum',
    'nav.cost': 'Biaya',
    'nav.registration': 'Tata Cara Pendaftaran',
    'button.login': 'Masuk',
    'button.register': 'Daftar Sekarang',
    'button.logout': 'Keluar',
    
    // Hero Section
    'hero.title': 'Selamat Datang di Program S3 STIE Mahardhika',
    'hero.subtitle': 'Mewujudkan Kepemimpinan Akademik dan Inovasi Global',
    'hero.description': 'Bergabunglah dengan para pemikir visioner yang membangun masa depan ekonomi dan bisnis melalui riset unggulan dan kolaborasi berkelanjutan.',
    'hero.cta': 'Daftar Sekarang',

    'cost.title': 'Biaya Pendidikan',
    'cost.subtitle': 'Program Doktor (S3) STIE Mahardhika',
    'cost.schedule.title': 'Program Reguler',
    'cost.schedule.description': 'Perkuliahan diselenggarakan pada hari Jumat Sore dan Sabtu.',
    'cost.details.title': 'Rincian Biaya',
    'cost.details.item1': 'Pendaftaran',
    'cost.details.item2': 'Matrikulasi',
    'cost.details.item3': 'Uang Kuliah Tunggal (UKT) per semester',
    'cost.cta': 'Daftar Sekarang',
    
    // Features
    'features.title': 'Mengapa Memilih STIE Mahardhika?',
    'features.quality': 'Kualitas Pendidikan Terbaik',
    'features.quality.desc': 'Kurikulum yang disesuaikan dengan kebutuhan industri',
    'features.faculty': 'Dosen Berpengalaman',
    'features.faculty.desc': 'Dosen yang ahli di bidangnya masing-masing',
    'features.facility': 'Fasilitas Lengkap',
    'features.facility.desc': 'Fasilitas modern untuk mendukung pembelajaran',
    'features.career': 'Bantuan Karir',
    'features.career.desc': 'Bimbingan karir dan penempatan kerja',
    
    // Process Timeline
    'process.title': 'Proses Pendaftaran',
    'process.step1': 'Daftar Online',
    'process.step1.desc': 'Isi formulir pendaftaran secara online',
    'process.step2': 'Upload Dokumen',
    'process.step2.desc': 'Upload dokumen yang diperlukan',
    'process.step3': 'Verifikasi',
    'process.step3.desc': 'Tim kami akan memverifikasi dokumen Anda',
    'process.step4': 'Konfirmasi',
    'process.step4.desc': 'Terima konfirmasi pendaftaran',
    
    // Requirements
    'requirements.title': 'Persyaratan Pendaftaran',
    'requirements.academic': 'Persyaratan Akademik',
    'requirements.academic.desc': 'Lulusan SMA/SMK sederajat',
    'requirements.documents': 'Dokumen yang Diperlukan',
    'requirements.documents.desc': 'Fotokopi ijazah, transkrip, dan KTP',
    'requirements.photo': 'Pas Foto',
    'requirements.photo.desc': 'Pas foto 3x4 sebanyak 2 lembar',
    'requirements.toefl': 'TOEFL/IELTS',
    'requirements.toefl.desc': 'Kemampuan bahasa Inggris',
    'requirements.recommendation': 'Surat Rekomendasi',
    'requirements.recommendation.desc': 'Referensi akademik',
    'requirements.proposal': 'Proposal Disertasi',
    'requirements.proposal.desc': 'Rencana penelitian',
    
    // Registration Steps
    'registration.title': 'Langkah-langkah Pendaftaran',
    'registration.online': 'Pendaftaran Online',
    'registration.online.desc': 'Daftar melalui website resmi',
    'registration.payment': 'Pembayaran',
    'registration.payment.desc': 'Lakukan pembayaran biaya pendaftaran',
    'registration.test': 'Tes Masuk',
    'registration.test.desc': 'Ikuti tes masuk sesuai jadwal',
    'registration.result': 'Pengumuman',
    'registration.result.desc': 'Lihat hasil seleksi di website',

		"registration.intro.title": "Tata Cara Pendaftaran",
		"registration.intro.line1":
			"Program Doktor Ilmu Manajemen membuka pendaftaran mahasiswa baru untuk kelas Reguler (Perkuliahan diselenggarakan pada hari Jumat Sore dan Sabtu).",
		"registration.intro.line2":
			"Pendaftaran mahasiswa baru Program Pascasarjana dilakukan secara online melalui website Seleksi Masuk STIE Mahardhika Surabaya.",
		"registration.cta.button": "Kunjungi Website Pendaftaran",

		"registration.step1.title": "Pembayaran Registrasi",
		"registration.step1.content":
			"Melakukan pembayaran biaya pendaftaran dan biaya tes seleksi masuk sebesar Rp. 500.000 untuk biaya registrasi.",

		"registration.step2.title": "Lengkapi Formulir & Berkas",
		"registration.step2.content":
			"Melakukan registrasi dengan melengkapi formulir isian pada halaman website. Setelah data terisi dan memperoleh username serta password, calon pendaftar diminta untuk melengkapi seluruh berkas pendaftaran melalui website PMB STIE Mahardhika.",
		"registration.step2.docs.title": "Berkas pendaftaran yang harus diunggah:",
		"registration.step2.docs.item1":
			"Salinan Ijazah Sarjana dan Magister yang telah disahkan oleh pejabat yang berwenang.",
		"registration.step2.docs.item2":
			"Salinan daftar nilai Sarjana dan Magister yang telah disahkan. Bagi lulusan PTS yang lulus sebelum kebijakan ujian Negara dihapuskan, harus menyerahkan nilai ujian Negara.",
		"registration.step2.docs.item3":
			"Salinan sertifikat Akreditasi BAN-PT Program Studi Magister yang berlaku saat tahun kelulusan.",
		"registration.step2.docs.item4": "Salinan KTP (Kartu Tanda Penduduk).",
		"registration.step2.docs.item5":
			"Salinan Sertifikat Test Potensi Akademik (TPA) OTO BAPPENAS dengan nilai TPA > 500.",
		"registration.step2.docs.item6":
			"Salinan Sertifikat TOEFL dengan nilai TOEFL > 500.",
		"registration.step2.docs.item7":
			"Salinan transkrip program Doktor yang telah disahkan (bagi mahasiswa pindahan).",
		"registration.step2.docs.item8":
			"Surat rekomendasi dari dua orang yang mampu memberikan jaminan kelayakan akademik pelamar.",
		"registration.step2.docs.item9":
			"Surat keterangan resmi dari penyandang dana studi.",
		"registration.step2.docs.item10":
			"Surat keterangan sehat dan bebas narkoba dari instansi yang berwenang.",
		"registration.step2.docs.item11":
			"Surat tugas/ijin dari atasan (jika pelamar telah bekerja).",
		"registration.step2.docs.item12":
			"Proposal Disertasi (Rencana Penelitian) Jika sudah ada.",
		"registration.step2.docs.item13":
			"Pas foto berwarna terbaru ukuran 4x6 (4 lembar) berlatar belakang biru.",
		"registration.step2.docs.item14": "Daftar Riwayat Hidup.",

		"registration.step3.title": "Tunggu Informasi Wawancara",
		"registration.step3.content":
			"Menunggu informasi proses wawancara yang akan diumumkan di website pmbs3.stiemahardhika.ac.id / PMB S3 STIE Mahardhika.",

		"registration.step4.title": "Proses Wawancara",
		"registration.step4.content":
			"Semua berkas pendaftaran wajib dibawa saat wawancara (rangkap 2) termasuk berkas yang telah diunggah.",
    
    // Footer
    'footer.about': 'Tentang Kami',
    'footer.contact': 'Kontak',
    'footer.address': 'Alamat',
    'footer.phone': 'Telepon',
    'footer.email': 'Email',
    'footer.copyright': '© 2024 STIE Mahardhika. Semua hak dilindungi.',
    
    // Language Selector
    'language.selector': 'Bahasa',
    'language.indonesian': 'Indonesia',
    'language.english': 'English',
    'language.chinese': '中文',
    
    // Dashboard Pendaftar
    'dashboard.welcome': 'Selamat Datang, {name}!',
    'dashboard.status.desc': 'Status pendaftaran Anda dapat dipantau di bawah ini.',
    'dashboard.status.title': 'Status Pendaftaran',
    'dashboard.notifications': 'Notifikasi',
    'dashboard.quick.actions': 'Aksi Cepat',
    'dashboard.access': 'Akses',
    'dashboard.tips': '💡 Tips:',
    'dashboard.tips.desc': 'Pastikan semua dokumen sudah diupload sebelum batas waktu yang ditentukan untuk menghindari keterlambatan proses verifikasi.',
    
    // Status Kelulusan
    'status.accepted.title': '🎉 Selamat! Anda DITERIMA',
    'status.accepted.desc': 'Anda telah dinyatakan LULUS seleksi Program Studi S3 STIE Mahardhika',
    'status.accepted.view.detail': 'Lihat Detail',
    'status.accepted.download.letter': 'Download Surat',
    'status.rejected.title': 'Pengumuman Hasil Seleksi',
    'status.rejected.desc': 'Mohon maaf, Anda belum berhasil pada seleksi kali ini. Jangan menyerah! Anda dapat mencoba lagi pada periode berikutnya.',
    'status.rejected.view.feedback': 'Lihat Feedback',
    'status.rejected.registration.info': 'Info Pendaftaran',
    
    // Notifikasi
    'notification.toefl.warning': 'Dokumen TOEFL belum sesuai, silakan upload ulang',
    'notification.payment.verified': 'Pembayaran Anda telah diverifikasi',
    'notification.time.2hours': '2 jam yang lalu',
    'notification.time.1day': '1 hari yang lalu',
    
    // Quick Actions
    'quick.upload.documents': 'Upload Dokumen',
    'quick.view.announcement': 'Lihat Pengumuman',
    'quick.download.guide': 'Download Panduan',
    
    // Login Page
    'login.title': 'Pendaftaran Program Doktor Ilmu Manajemen',
    'login.description': 'Bergabunglah dengan Program Doktor Ilmu Manajemen di Sekolah Tinggi Ilmu Ekonomi Mahardhika Surabaya untuk mengembangkan keahlian manajerial Anda dengan kurikulum berstandar internasional dan dosen berpengalaman.',
    'login.accreditation': 'Akreditasi unggul dan jaringan akademik global',
    'login.signin.title': 'Masuk',
    'login.signin.subtitle': 'Masukkan kredensial Anda untuk mengakses akun',
    'login.email.label': 'Alamat Email',
    'login.email.placeholder': 'anda@contoh.com',
    'login.password.label': 'Kata Sandi',
    'login.password.placeholder': '••••••••',
    'login.remember': 'Ingat saya',
    'login.forgot': 'Lupa kata sandi?',
    'login.signin.button': 'Masuk',
    'login.no.account': 'Belum punya akun?',
    'login.create.account': 'Buat sekarang',
    
    // Curriculum Page
    'curriculum.title': 'Struktur Kurikulum',
    'curriculum.subtitle': 'Program Doktor Ilmu Manajemen STIE Mahardhika',
    'curriculum.description': 'Kurikulum dirancang secara komprehensif untuk menghasilkan peneliti dan akademisi berkualitas tinggi',
    'curriculum.total.sks': 'Total SKS Program',
    'curriculum.concentrations': 'Konsentrasi Minat',
    'curriculum.semesters': 'Semester',
    'curriculum.matriculation.sks': 'SKS Matrikulasi',
    'curriculum.matriculation.title': 'Mata Kuliah Matrikulasi',
    'curriculum.matriculation.subtitle': 'Program leveling untuk mahasiswa',
    'curriculum.matriculation.info.title': 'Informasi Matrikulasi',
    'curriculum.matriculation.info.1': 'Mata kuliah matrikulasi adalah program leveling untuk mahasiswa yang latar belakang akademiknya tidak linear dengan manajemen',
    'curriculum.matriculation.info.2': 'Dilaksanakan di luar kurikulum utama program doktor',
    'curriculum.matriculation.info.3': 'Bertujuan untuk menyelaraskan pengetahuan dasar mahasiswa sebelum memulai program doktor',
    'curriculum.core.title': 'Mata Kuliah Wajib Program',
    'curriculum.core.subtitle': 'Fundamental untuk semua mahasiswa',
    'curriculum.concentration.title': 'Mata Kuliah Konsentrasi',
    'curriculum.concentration.subtitle': 'Pilih salah satu dari dua konsentrasi minat yang tersedia. Setiap konsentrasi terdiri dari 9 SKS mata kuliah yang harus diambil secara lengkap sesuai bidang keahlian yang dipilih.',
    'curriculum.concentration.info': 'Mahasiswa wajib memilih dan menyelesaikan salah satu konsentrasi secara lengkap (9 SKS)',
    'curriculum.dissertation.title': 'Persyaratan Disertasi',
    'curriculum.dissertation.1': 'Kualifikasi Proposal Disertasi (Semester III) - 3 SKS',
    'curriculum.dissertation.2': 'Penelitian Disertasi dengan Ujian Proposal dan Ujian Kelayakan (Semester IV) - 9 SKS',
    'curriculum.dissertation.3': 'Publikasi Internasional (Semester V) - 9 SKS',
    'curriculum.dissertation.4': 'Disertasi dengan Ujian Tertutup dan Ujian Terbuka (Semester VI) - 9 SKS',
    'curriculum.summary.title': 'Ringkasan Beban Studi',
    'curriculum.summary.core': 'SKS Wajib',
    'curriculum.summary.concentration': 'SKS Konsentrasi',
    'curriculum.summary.matriculation': 'SKS Matrikulasi',
    'curriculum.summary.total': 'TOTAL SKS',
    'curriculum.summary.core.desc': 'Semester I-VI',
    'curriculum.summary.concentration.desc': 'Satu Konsentrasi Pilihan',
    'curriculum.summary.matriculation.desc': 'Di Luar Program',
    'curriculum.summary.total.desc': 'Program Lengkap',
    'curriculum.roadmap.title': 'Roadmap Akademik',
    'curriculum.roadmap.year1': 'Tahun Pertama',
    'curriculum.roadmap.year2': 'Tahun Kedua',
    'curriculum.roadmap.year3': 'Tahun Ketiga',
    'curriculum.roadmap.year1.desc': 'Semester I-II',
    'curriculum.roadmap.year2.desc': 'Semester III-IV',
    'curriculum.roadmap.year3.desc': 'Semester V-VI',
    'curriculum.roadmap.year1.1': 'Mata kuliah wajib (Filsafat Ilmu, Metode Penelitian, Teori Manajemen Lanjutan)',
    'curriculum.roadmap.year1.2': 'Mata kuliah konsentrasi pilihan (MSDM atau Pemasaran)',
    'curriculum.roadmap.year1.3': 'Identifikasi topik penelitian disertasi',
    'curriculum.roadmap.year1.4': 'Persiapan proposal disertasi',
    'curriculum.roadmap.year2.1': 'Kualifikasi Proposal Disertasi (Semester III)',
    'curriculum.roadmap.year2.2': 'Penelitian Disertasi dengan Ujian Proposal',
    'curriculum.roadmap.year2.3': 'Ujian Kelayakan Hasil Penelitian',
    'curriculum.roadmap.year2.4': 'Penyelesaian tahap penelitian',
    'curriculum.roadmap.year3.1': 'Publikasi Internasional (Semester V)',
    'curriculum.roadmap.year3.2': 'Penyelesaian penulisan disertasi',
    'curriculum.roadmap.year3.3': 'Ujian Tertutup Disertasi (Semester VI)',
    'curriculum.roadmap.year3.4': 'Ujian Terbuka dan Wisuda',
    'curriculum.advantages.title': 'Keunggulan Program',
    'curriculum.advantages.1': 'Dosen pembimbing berpengalaman dengan rekam jejak publikasi internasional',
    'curriculum.advantages.2': 'Kurikulum berbasis riset dengan penekanan pada publikasi ilmiah',
    'curriculum.advantages.3': 'Fasilitas penelitian lengkap termasuk akses ke database jurnal internasional',
    'curriculum.advantages.4': 'Kolaborasi riset dengan universitas dan institusi penelitian terkemuka',
    'curriculum.advantages.5': 'Dukungan pendanaan untuk konferensi internasional dan publikasi',
    'curriculum.career.title': 'Prospek Karir Lulusan',
    'curriculum.career.1': 'Akademisi dan peneliti di perguruan tinggi',
    'curriculum.career.2': 'Konsultan manajemen dan bisnis senior',
    'curriculum.career.3': 'Eksekutif dan pemimpin organisasi',
    'curriculum.career.4': 'Analis kebijakan di lembaga pemerintah',
    'curriculum.career.5': 'Peneliti di lembaga riset dan think tank',
    'curriculum.cta.title': 'Siap Memulai Perjalanan Akademis Anda?',
    'curriculum.cta.description': 'Bergabunglah dengan Program Doktor Ilmu Manajemen dan kembangkan potensi penelitian Anda untuk memberikan kontribusi nyata pada dunia akademis dan praktik manajemen',
    'curriculum.cta.register': 'Daftar Sekarang',
    'curriculum.cta.brochure': 'Unduh Brosur',
    
    // Modal Registration
    'modal.registration.title': 'Pendaftaran Online',
    'modal.registration.step': 'Langkah',
    'modal.registration.of': 'dari',
    'modal.registration.personal.info': 'Informasi Pribadi',
    'modal.registration.academic.info': 'Informasi Akademik',
    'modal.registration.fullname.placeholder': 'Nama Lengkap',
    'modal.registration.email.placeholder': 'Email',
    'modal.registration.phone.placeholder': 'Nomor HP (10-13 digit)',
    'modal.registration.ktp.placeholder': 'Nomor KTP (16 digit)',
    'modal.registration.upload.photo': 'Upload Foto',
    'modal.registration.search.s1': 'Cari Asal Perguruan Tinggi S1',
    'modal.registration.search.s2': 'Cari Asal Perguruan Tinggi S2',
    'modal.registration.gpa.s1.placeholder': 'IPK S1 (0-4)',
    'modal.registration.gpa.s2.placeholder': 'IPK S2 (0-4)',
    'modal.registration.loading.universities': 'Memuat universitas...',
    'modal.registration.file.selected': 'File terpilih:',
    'modal.registration.back': 'Kembali',
    'modal.registration.next': 'Lanjut',
    'modal.registration.submit': 'Daftar',
    'modal.registration.success': 'Formulir berhasil dikirim!',
    'modal.registration.error.api': 'Gagal memuat data universitas',
    
    // Validation Messages
    'validation.fullname.required': 'Nama lengkap wajib diisi',
    'validation.email.required': 'Email wajib diisi',
    'validation.email.invalid': 'Format email tidak valid',
    'validation.phone.required': 'Nomor HP wajib diisi',
    'validation.phone.invalid': 'Nomor HP harus 10-13 digit',
    'validation.ktp.required': 'Nomor KTP wajib diisi',
    'validation.ktp.invalid': 'Nomor KTP harus 16 digit',
    'validation.photo.required': 'Foto wajib diunggah',
    'validation.s1.university.required': 'Asal perguruan tinggi S1 wajib diisi',
    'validation.s1.gpa.required': 'IPK S1 wajib diisi',
    'validation.s1.gpa.invalid': 'IPK harus antara 0-4',
    'validation.s2.university.required': 'Asal perguruan tinggi S2 wajib diisi',
    'validation.s2.gpa.required': 'IPK S2 wajib diisi',
    'validation.s2.gpa.invalid': 'IPK harus antara 0-4',
    'curriculum.info.flexible': 'Jadwal Fleksibel',
    'curriculum.info.flexible.desc': 'Perkuliahan dirancang untuk profesional yang bekerja dengan jadwal weekend dan executive class',
    'curriculum.info.accreditation': 'Akreditasi',
    'curriculum.info.accreditation.desc': 'Program terakreditasi dengan standar nasional pendidikan tinggi Indonesia',
    'curriculum.info.publication': 'Publikasi Ilmiah',
    'curriculum.info.publication.desc': 'Mahasiswa didorong untuk publikasi di jurnal nasional dan internasional bereputasi',
    'curriculum.duration.normal': 'Tahun',
    'curriculum.duration.normal.desc': 'Durasi Normal',
    'curriculum.duration.max': 'Tahun',
    'curriculum.duration.max.desc': 'Maksimal Studi',
    'curriculum.ratio': 'Rasio Dosen:Mahasiswa',
    'curriculum.table.no': 'No',
    'curriculum.table.code': 'Kode MK',
    'curriculum.table.name': 'Nama Mata Kuliah',
    'curriculum.table.sks': 'SKS',
    'curriculum.table.semester': 'Semester',
    'curriculum.table.type': 'Jenis',
    'curriculum.table.total': 'Total SKS',
    'curriculum.type.required': 'Wajib',
    'curriculum.type.concentration': 'Konsentrasi',
    'curriculum.type.matriculation': 'Matrikulasi',
    
    // Course Names
    'curriculum.course.economic.theory': 'Teori Ekonomi',
    'curriculum.course.management.theory': 'Teori Manajemen',
    'curriculum.course.advanced.statistics': 'Statistik Lanjutan',
    'curriculum.course.philosophy.science': 'Filsafat Ilmu',
    'curriculum.course.research.methods': 'Metode Penelitian',
    'curriculum.course.advanced.management': 'Teori Manajemen Lanjutan',
    'curriculum.course.dissertation.qualification': 'Kualifikasi Proposal Disertasi',
    'curriculum.course.dissertation.research': 'Penelitian Disertasi',
    'curriculum.course.international.publication': 'Publikasi Internasional',
    'curriculum.course.dissertation': 'Disertasi',
    'curriculum.course.hrm': 'Manajemen Sumber Daya Manusia',
    'curriculum.course.human.capital': 'Human Capital Strategic and Development',
    'curriculum.course.hrm.leadership': 'Manajemen Sumber Daya Manusia dalam Kepemimpinan',
    'curriculum.course.marketing': 'Manajemen Pemasaran',
    'curriculum.course.marketing.strategy': 'Strategi Pemasaran',
    'curriculum.course.consumer.behavior': 'Teori Perilaku Konsumen',
    
    // Concentration Names
    'curriculum.concentration.hrm': 'Manajemen Sumberdaya Manusia',
    'curriculum.concentration.marketing': 'Manajemen Pemasaran',
  },
  en: {
    // Header
    'nav.home': 'Home',
    'nav.profile': 'Program Profile',
    'nav.curriculum': 'Curriculum',
    'nav.cost': 'Cost',
    'nav.registration': 'Registration Process',
    'button.login': 'Login',
    'button.register': 'Register Now',
    'button.logout': 'Logout',
    
    // Hero Section
    'hero.title': 'Welcome to the Doctoral Program at STIE Mahardhika',
    'hero.subtitle': 'Realizing Academic Leadership and Global Innovation',
    'hero.description': 'Join visionary thinkers who are shaping the future of economics and business through excellent research and sustainable collaboration.',
    'hero.cta': 'Register Now',

    'cost.title': 'Tuition Fees',
    'cost.subtitle': 'Doctoral Program (S3) at STIE Mahardhika',
    'cost.schedule.title': 'Regular Program',
    'cost.schedule.description': 'Lectures are held on Friday afternoons and Saturdays.',
    'cost.details.title': 'Fee Details',
    'cost.details.item1': 'Registration',
    'cost.details.item2': 'Matriculation',
    'cost.details.item3': 'Single Tuition Fee (UKT) per semester',
    'cost.cta': 'Register Now',
    
    // Features
    'features.title': 'Why Choose STIE Mahardhika?',
    'features.quality': 'Best Education Quality',
    'features.quality.desc': 'Curriculum tailored to industry needs',
    'features.faculty': 'Experienced Lecturers',
    'features.faculty.desc': 'Lecturers who are experts in their respective fields',
    'features.facility': 'Complete Facilities',
    'features.facility.desc': 'Modern facilities to support learning',
    'features.career': 'Career Support',
    'features.career.desc': 'Career guidance and job placement',
    
    // Process Timeline
    'process.title': 'Registration Process',
    'process.step1': 'Online Registration',
    'process.step1.desc': 'Fill out the registration form online',
    'process.step2': 'Upload Documents',
    'process.step2.desc': 'Upload required documents',
    'process.step3': 'Verification',
    'process.step3.desc': 'Our team will verify your documents',
    'process.step4': 'Confirmation',
    'process.step4.desc': 'Receive registration confirmation',
    
    // Requirements
    'requirements.title': 'Registration Requirements',
    'requirements.academic': 'Academic Requirements',
    'requirements.academic.desc': 'High school/equivalent graduate',
    'requirements.documents': 'Required Documents',
    'requirements.documents.desc': 'Photocopy of diploma, transcript, and ID card',
    'requirements.photo': 'Passport Photo',
    'requirements.photo.desc': '3x4 passport photos, 2 pieces',
    'requirements.toefl': 'TOEFL/IELTS',
    'requirements.toefl.desc': 'English language proficiency',
    'requirements.recommendation': 'Recommendation Letter',
    'requirements.recommendation.desc': 'Academic reference',
    'requirements.proposal': 'Dissertation Proposal',
    'requirements.proposal.desc': 'Research plan',
    
    // Registration Steps
    'registration.title': 'Registration Steps',
    'registration.online': 'Online Registration',
    'registration.online.desc': 'Register through official website',
    'registration.payment': 'Payment',
    'registration.payment.desc': 'Make registration fee payment',
    'registration.test': 'Entrance Test',
    'registration.test.desc': 'Take entrance test according to schedule',
    'registration.result': 'Announcement',
    'registration.result.desc': 'View selection results on website',
    
    "registration.intro.title": "Registration Procedure",
    "registration.intro.line1": "The Doctor of Management Science Program is opening new student admissions for the Regular class (Lectures are held on Friday Afternoons and Saturdays).",
    "registration.intro.line2": "New postgraduate student registration is conducted online through the STIE Mahardhika Surabaya Entrance Selection website.",
    "registration.cta.button": "Visit Registration Website",
    "registration.step1.title": "Registration Payment",
    "registration.step1.content": "Make the registration fee and entrance selection test payment of IDR 500,000 for the registration fee.",
    "registration.step2.title": "Complete Form & Documents",
    "registration.step2.content": "Register by completing the application form on the website. After the data is filled and a username and password have been obtained, prospective applicants are required to complete all registration documents through the STIE Mahardhika PMB website.",
    "registration.step2.docs.title": "Required documents to be uploaded:",
    "registration.step2.docs.item1": "Copy of legalized Bachelor's and Master's degree certificates.",
    "registration.step2.docs.item2": "Copy of legalized Bachelor's and Master's academic transcripts. For graduates from private universities who graduated before the state examination policy was abolished, the state examination scores must be submitted.",
    "registration.step2.docs.item3": "Copy of the BAN-PT Accreditation certificate for the Master's Program valid at the time of graduation.",
    "registration.step2.docs.item4": "Copy of ID Card (KTP).",
    "registration.step2.docs.item5": "Copy of the Academic Potential Test (TPA) OTO BAPPENAS Certificate with a score > 500.",
    "registration.step2.docs.item6": "Copy of a TOEFL Certificate with a score > 500.",
    "registration.step2.docs.item7": "Copy of the legalized Doctoral program transcript (for transfer students).",
    "registration.step2.docs.item8": "Recommendation letters from two individuals who can guarantee the applicant's academic eligibility.",
    "registration.step2.docs.item9": "Official statement letter from the study sponsor.",
    "registration.step2.docs.item10": "Health certificate, including being drug-free, from an authorized institution.",
    "registration.step2.docs.item11": "Assignment/permission letter from a superior (if the applicant is employed) stating that the applicant is released from their duties.",
    "registration.step2.docs.item12": "Dissertation Proposal (Research Plan), if available.",
    "registration.step2.docs.item13": "Four recent 4x6 cm color photographs with a blue background.",
    "registration.step2.docs.item14": "Curriculum Vitae (CV).",
    "registration.step3.title": "Wait for Interview Information",
    "registration.step3.content": "Wait for information on the interview process, which will be announced on the pmbs3.stiemahardhika.ac.id / PMB S3 STIE Mahardhika website.",
    "registration.step4.title": "Interview Process",
    "registration.step4.content": "All registration documents must be brought to the interview (in duplicate), including the uploaded files.",

    // Footer
    'footer.about': 'About Us',
    'footer.contact': 'Contact',
    'footer.address': 'Address',
    'footer.phone': 'Phone',
    'footer.email': 'Email',
    'footer.copyright': '© 2024 STIE Mahardhika. All rights reserved.',
    
    // Language Selector
    'language.selector': 'Language',
    'language.indonesian': 'Indonesia',
    'language.english': 'English',
    'language.chinese': '中文',
    
    // Dashboard Pendaftar
    'dashboard.welcome': 'Welcome, {name}!',
    'dashboard.status.desc': 'Your registration status can be monitored below.',
    'dashboard.status.title': 'Registration Status',
    'dashboard.notifications': 'Notifications',
    'dashboard.quick.actions': 'Quick Actions',
    'dashboard.access': 'Access',
    'dashboard.tips': '💡 Tips:',
    'dashboard.tips.desc': 'Make sure all documents are uploaded before the specified deadline to avoid delays in the verification process.',
    
    // Status Kelulusan
    'status.accepted.title': '🎉 Congratulations! You are ACCEPTED',
    'status.accepted.desc': 'You have been declared PASSED in the S3 STIE Mahardhika Program selection',
    'status.accepted.view.detail': 'View Details',
    'status.accepted.download.letter': 'Download Letter',
    'status.rejected.title': 'Selection Results Announcement',
    'status.rejected.desc': 'Sorry, you were not successful in this selection. Don\'t give up! You can try again in the next period.',
    'status.rejected.view.feedback': 'View Feedback',
    'status.rejected.registration.info': 'Registration Info',
    
    // Notifikasi
    'notification.toefl.warning': 'TOEFL document is not appropriate, please re-upload',
    'notification.payment.verified': 'Your payment has been verified',
    'notification.time.2hours': '2 hours ago',
    'notification.time.1day': '1 day ago',
    
    // Quick Actions
    'quick.upload.documents': 'Upload Documents',
    'quick.view.announcement': 'View Announcement',
    'quick.download.guide': 'Download Guide',
    
    // Login Page
    'login.title': 'Doctor of Management Science Program Registration',
    'login.description': 'Join the Doctor of Management Science Program at Sekolah Tinggi Ilmu Ekonomi Mahardhika Surabaya to develop your managerial expertise with internationally standardized curriculum and experienced lecturers.',
    'login.accreditation': 'Excellent accreditation and global academic network',
    'login.signin.title': 'Sign In',
    'login.signin.subtitle': 'Enter your credentials to access your account',
    'login.email.label': 'Email Address',
    'login.email.placeholder': 'you@example.com',
    'login.password.label': 'Password',
    'login.password.placeholder': '••••••••',
    'login.remember': 'Remember me',
    'login.forgot': 'Forgot password?',
    'login.signin.button': 'Sign In',
    'login.no.account': 'Don\'t have an account?',
    'login.create.account': 'Create one now',
    
    // Curriculum Page
    'curriculum.title': 'Curriculum Structure',
    'curriculum.subtitle': 'Doctor of Management Science Program at STIE Mahardhika',
    'curriculum.description': 'The curriculum is designed comprehensively to produce high-quality researchers and academics',
    'curriculum.total.sks': 'Total Program Credits',
    'curriculum.concentrations': 'Concentration Areas',
    'curriculum.semesters': 'Semesters',
    'curriculum.matriculation.sks': 'Matriculation Credits',
    'curriculum.matriculation.title': 'Matriculation Courses',
    'curriculum.matriculation.subtitle': 'Leveling program for students',
    'curriculum.matriculation.info.title': 'Matriculation Information',
    'curriculum.matriculation.info.1': 'Matriculation courses are leveling programs for students whose academic background is not directly related to management',
    'curriculum.matriculation.info.2': 'Conducted outside the main doctoral program curriculum',
    'curriculum.matriculation.info.3': 'Aims to align students\' basic knowledge before starting the doctoral program',
    'curriculum.core.title': 'Core Program Courses',
    'curriculum.core.subtitle': 'Fundamental for all students',
    'curriculum.concentration.title': 'Concentration Courses',
    'curriculum.concentration.subtitle': 'Choose one of the two available concentration areas. Each concentration consists of 9 credits that must be taken completely according to the chosen field of expertise.',
    'curriculum.concentration.info': 'Students must choose and complete one concentration completely (9 credits)',
    'curriculum.dissertation.title': 'Dissertation Requirements',
    'curriculum.dissertation.1': 'Dissertation Proposal Qualification (Semester III) - 3 credits',
    'curriculum.dissertation.2': 'Dissertation Research with Proposal and Feasibility Exams (Semester IV) - 9 credits',
    'curriculum.dissertation.3': 'International Publication (Semester V) - 9 credits',
    'curriculum.dissertation.4': 'Dissertation with Closed and Open Exams (Semester VI) - 9 credits',
    'curriculum.summary.title': 'Study Load Summary',
    'curriculum.summary.core': 'Core Credits',
    'curriculum.summary.concentration': 'Concentration Credits',
    'curriculum.summary.matriculation': 'Matriculation Credits',
    'curriculum.summary.total': 'TOTAL CREDITS',
    'curriculum.summary.core.desc': 'Semester I-VI',
    'curriculum.summary.concentration.desc': 'One Chosen Concentration',
    'curriculum.summary.matriculation.desc': 'Outside Program',
    'curriculum.summary.total.desc': 'Complete Program',
    'curriculum.roadmap.title': 'Academic Roadmap',
    'curriculum.roadmap.year1': 'First Year',
    'curriculum.roadmap.year2': 'Second Year',
    'curriculum.roadmap.year3': 'Third Year',
    'curriculum.roadmap.year1.desc': 'Semester I-II',
    'curriculum.roadmap.year2.desc': 'Semester III-IV',
    'curriculum.roadmap.year3.desc': 'Semester V-VI',
    'curriculum.roadmap.year1.1': 'Core courses (Philosophy of Science, Research Methods, Advanced Management Theory)',
    'curriculum.roadmap.year1.2': 'Elective concentration courses (HRM or Marketing)',
    'curriculum.roadmap.year1.3': 'Identify dissertation research topic',
    'curriculum.roadmap.year1.4': 'Prepare dissertation proposal',
    'curriculum.roadmap.year2.1': 'Dissertation Proposal Qualification (Semester III)',
    'curriculum.roadmap.year2.2': 'Dissertation Research with Proposal Exam',
    'curriculum.roadmap.year2.3': 'Research Outcome Feasibility Exam',
    'curriculum.roadmap.year2.4': 'Complete research phase',
    'curriculum.roadmap.year3.1': 'International Publication (Semester V)',
    'curriculum.roadmap.year3.2': 'Complete dissertation writing',
    'curriculum.roadmap.year3.3': 'Closed Dissertation Exam (Semester VI)',
    'curriculum.roadmap.year3.4': 'Open Exam and Graduation',
    'curriculum.advantages.title': 'Program Advantages',
    'curriculum.advantages.1': 'Experienced supervisors with international publication track records',
    'curriculum.advantages.2': 'Research-based curriculum with emphasis on scientific publications',
    'curriculum.advantages.3': 'Complete research facilities including access to international journal databases',
    'curriculum.advantages.4': 'Research collaboration with leading universities and research institutions',
    'curriculum.advantages.5': 'Funding support for international conferences and publications',
    'curriculum.career.title': 'Graduate Career Prospects',
    'curriculum.career.1': 'Academics and researchers at universities',
    'curriculum.career.2': 'Senior management and business consultants',
    'curriculum.career.3': 'Executives and organizational leaders',
    'curriculum.career.4': 'Policy analysts at government institutions',
    'curriculum.career.5': 'Researchers at research institutions and think tanks',
    'curriculum.cta.title': 'Ready to Start Your Academic Journey?',
    'curriculum.cta.description': 'Join the Doctor of Management Science Program and develop your research potential to make real contributions to the academic world and management practice',
    'curriculum.cta.register': 'Register Now',
    'curriculum.cta.brochure': 'Download Brochure',
    
    // Modal Registration
    'modal.registration.title': 'Online Registration',
    'modal.registration.step': 'Step',
    'modal.registration.of': 'of',
    'modal.registration.personal.info': 'Personal Information',
    'modal.registration.academic.info': 'Academic Information',
    'modal.registration.fullname.placeholder': 'Full Name',
    'modal.registration.email.placeholder': 'Email',
    'modal.registration.phone.placeholder': 'Phone Number (10-13 digits)',
    'modal.registration.ktp.placeholder': 'ID Number (16 digits)',
    'modal.registration.upload.photo': 'Upload Photo',
    'modal.registration.search.s1': 'Search S1 University',
    'modal.registration.search.s2': 'Search S2 University',
    'modal.registration.gpa.s1.placeholder': 'S1 GPA (0-4)',
    'modal.registration.gpa.s2.placeholder': 'S2 GPA (0-4)',
    'modal.registration.loading.universities': 'Loading universities...',
    'modal.registration.file.selected': 'File selected:',
    'modal.registration.back': 'Back',
    'modal.registration.next': 'Next',
    'modal.registration.submit': 'Register',
    'modal.registration.success': 'Form submitted successfully!',
    'modal.registration.error.api': 'Failed to load university data',
    
    // Validation Messages
    'validation.fullname.required': 'Full name is required',
    'validation.email.required': 'Email is required',
    'validation.email.invalid': 'Invalid email format',
    'validation.phone.required': 'Phone number is required',
    'validation.phone.invalid': 'Phone number must be 10-13 digits',
    'validation.ktp.required': 'ID number is required',
    'validation.ktp.invalid': 'ID number must be 16 digits',
    'validation.photo.required': 'Photo must be uploaded',
    'validation.s1.university.required': 'S1 university is required',
    'validation.s1.gpa.required': 'S1 GPA is required',
    'validation.s1.gpa.invalid': 'GPA must be between 0-4',
    'validation.s2.university.required': 'S2 university is required',
    'validation.s2.gpa.required': 'S2 GPA is required',
    'validation.s2.gpa.invalid': 'GPA must be between 0-4',
    'curriculum.info.flexible': 'Flexible Schedule',
    'curriculum.info.flexible.desc': 'Lectures designed for working professionals with weekend and executive class schedules',
    'curriculum.info.accreditation': 'Accreditation',
    'curriculum.info.accreditation.desc': 'Program accredited with Indonesian national higher education standards',
    'curriculum.info.publication': 'Scientific Publication',
    'curriculum.info.publication.desc': 'Students are encouraged to publish in national and international reputable journals',
    'curriculum.duration.normal': 'Years',
    'curriculum.duration.normal.desc': 'Normal Duration',
    'curriculum.duration.max': 'Years',
    'curriculum.duration.max.desc': 'Maximum Study',
    'curriculum.ratio': 'Lecturer:Student Ratio',
    'curriculum.table.no': 'No',
    'curriculum.table.code': 'Course Code',
    'curriculum.table.name': 'Course Name',
    'curriculum.table.sks': 'Credits',
    'curriculum.table.semester': 'Semester',
    'curriculum.table.type': 'Type',
    'curriculum.table.total': 'Total Credits',
    'curriculum.type.required': 'Required',
    'curriculum.type.concentration': 'Concentration',
    'curriculum.type.matriculation': 'Matriculation',
    
    // Course Names
    'curriculum.course.economic.theory': 'Economic Theory',
    'curriculum.course.management.theory': 'Management Theory',
    'curriculum.course.advanced.statistics': 'Advanced Statistics',
    'curriculum.course.philosophy.science': 'Philosophy of Science',
    'curriculum.course.research.methods': 'Research Methods',
    'curriculum.course.advanced.management': 'Advanced Management Theory',
    'curriculum.course.dissertation.qualification': 'Dissertation Proposal Qualification',
    'curriculum.course.dissertation.research': 'Dissertation Research',
    'curriculum.course.international.publication': 'International Publication',
    'curriculum.course.dissertation': 'Dissertation',
    'curriculum.course.hrm': 'Human Resource Management',
    'curriculum.course.human.capital': 'Human Capital Strategic and Development',
    'curriculum.course.hrm.leadership': 'Human Resource Management in Leadership',
    'curriculum.course.marketing': 'Marketing Management',
    'curriculum.course.marketing.strategy': 'Marketing Strategy',
    'curriculum.course.consumer.behavior': 'Consumer Behavior Theory',
    
    // Concentration Names
    'curriculum.concentration.hrm': 'Human Resource Management',
    'curriculum.concentration.marketing': 'Marketing Management',
  },
  zh: {
    // Header
    'nav.home': '首页',
    'nav.profile': '专业简介',
    'nav.curriculum': '课程',
    'nav.cost': '费用',
    'nav.registration': '注册流程',
    'button.login': '登录',
    'button.register': '立即注册',
    'button.logout': '登出',
    
    // Hero Section
    'hero.title': '欢迎来到 STIE Mahardhika 博士项目',
    'hero.subtitle': '实现学术领导力和全球创新',
    'hero.description': '与富有远见的思想家一起，通过卓越的研究和可持续的合作，塑造经济和商业的未来。',
    'hero.cta': '现在注册',

    'cost.title': '学费',
    'cost.subtitle': 'STIE Mahardhika 博士项目 (S3)',
    'cost.schedule.title': '常规课程',
    'cost.schedule.description': '讲座于周五下午和周六举行。',
    'cost.details.title': '费用明细',
    'cost.details.item1': '注册费',
    'cost.details.item2': '预科费',
    'cost.details.item3': '每学期单一学费 (UKT)',
    'cost.cta': '现在注册',
    
    // Features
    'features.title': '为什么选择STIE Mahardhika？',
    'features.quality': '最佳教育质量',
    'features.quality.desc': '根据行业需求定制的课程',
    'features.faculty': '经验丰富的讲师',
    'features.faculty.desc': '各自领域的专家讲师',
    'features.facility': '完善的设施',
    'features.facility.desc': '支持学习的现代化设施',
    'features.career': '职业支持',
    'features.career.desc': '职业指导和就业安置',
    
    // Process Timeline
    'process.title': '注册流程',
    'process.step1': '在线注册',
    'process.step1.desc': '在线填写注册表格',
    'process.step2': '上传文件',
    'process.step2.desc': '上传所需文件',
    'process.step3': '验证',
    'process.step3.desc': '我们的团队将验证您的文件',
    'process.step4': '确认',
    'process.step4.desc': '接收注册确认',
    
    // Requirements
    'requirements.title': '注册要求',
    'requirements.academic': '学术要求',
    'requirements.academic.desc': '高中/同等学历毕业生',
    'requirements.documents': '所需文件',
    'requirements.documents.desc': '文凭、成绩单和身份证复印件',
    'requirements.photo': '护照照片',
    'requirements.photo.desc': '3x4护照照片，2张',
    'requirements.toefl': 'TOEFL/IELTS',
    'requirements.toefl.desc': '英语语言能力',
    'requirements.recommendation': '推荐信',
    'requirements.recommendation.desc': '学术推荐',
    'requirements.proposal': '论文提案',
    'requirements.proposal.desc': '研究计划',
    
    // Registration Steps
    'registration.title': '注册步骤',
    'registration.online': '在线注册',
    'registration.online.desc': '通过官方网站注册',
    'registration.payment': '付款',
    'registration.payment.desc': '支付注册费',
    'registration.test': '入学考试',
    'registration.test.desc': '按时间表参加入学考试',
    'registration.result': '公告',
    'registration.result.desc': '在网站上查看选拔结果',
    
    "registration.intro.title": "注册流程",
    "registration.intro.line1": "管理科学博士项目正在为常规班招收新生（讲座在周五下午和周六举行）。",
    "registration.intro.line2": "研究生新生注册通过 STIE Mahardhika 泗水入学选拔网站在线进行。",
    "registration.cta.button": "访问注册网站",
    "registration.step1.title": "支付注册费",
    "registration.step1.content": "支付注册费和入学选拔测试费共计 500,000 印尼盾。",
    "registration.step2.title": "填写表格并上传文件",
    "registration.step2.content": "在网站上填写申请表进行注册。填写数据并获取用户名和密码后，申请人需通过 STIE Mahardhika PMB 网站完成所有注册文件的上传。",
    "registration.step2.docs.title": "需要上传的文件:",
    "registration.step2.docs.item1": "经认证的学士和硕士学位证书复印件。",
    "registration.step2.docs.item2": "经认证的学士和硕士成绩单复印件。对于在国家考试政策废除前毕业的私立大学毕业生，必须提交国家考试成绩。",
    "registration.step2.docs.item3": "毕业时有效的硕士课程 BAN-PT 认证证书复印件。",
    "registration.step2.docs.item4": "身份证（KTP）复印件。",
    "registration.step2.docs.item5": "学术潜力测试（TPA）OTO BAPPENAS 证书复印件，分数需 > 500。",
    "registration.step2.docs.item6": "托福（TOEFL）证书复印件，分数需 > 500。",
    "registration.step2.docs.item7": "经认证的博士课程成绩单复印件（适用于转学生）。",
    "registration.step2.docs.item8": "两名能保证申请人学术资格的推荐人的推荐信。",
    "registration.step2.docs.item9": "学习赞助方的官方声明信。",
    "registration.step2.docs.item10": "由授权机构出具的健康证明，包括无毒品证明。",
    "registration.step2.docs.item11": "上级出具的任务/许可信（如果申请人已就业），说明申请人已解除其职务。",
    "registration.step2.docs.item12": "论文计划（研究计划），如有。",
    "registration.step2.docs.item13": "四张近期 4x6 厘米蓝色背景的彩色照片。",
    "registration.step2.docs.item14": "个人简历。",
    "registration.step3.title": "等待面试信息",
    "registration.step3.content": "等待面试流程信息，相关信息将在 pmbs3.stiemahardhika.ac.id / PMB S3 STIE Mahardhika 网站上公布。",
    "registration.step4.title": "面试流程",
    "registration.step4.content": "所有注册文件（包括已上传的文件）必须在面试时携带（一式两份）。",    

    // Footer
    'footer.about': '关于我们',
    'footer.contact': '联系方式',
    'footer.address': '地址',
    'footer.phone': '电话',
    'footer.email': '邮箱',
    'footer.copyright': '© 2024 STIE Mahardhika. 版权所有.',
    
    // Language Selector
    'language.selector': '语言',
    'language.indonesian': 'Indonesia',
    'language.english': 'English',
    'language.chinese': '中文',
    
    // Dashboard Pendaftar
    'dashboard.welcome': '欢迎，{name}！',
    'dashboard.status.desc': '您的注册状态可以在下方监控。',
    'dashboard.status.title': '注册状态',
    'dashboard.notifications': '通知',
    'dashboard.quick.actions': '快速操作',
    'dashboard.access': '访问',
    'dashboard.tips': '💡 提示：',
    'dashboard.tips.desc': '确保在指定截止日期前上传所有文件，以避免验证过程延迟。',
    
    // Status Kelulusan
    'status.accepted.title': '🎉 恭喜！您已被录取',
    'status.accepted.desc': '您已被宣布通过STIE Mahardhika S3项目选拔',
    'status.accepted.view.detail': '查看详情',
    'status.accepted.download.letter': '下载信件',
    'status.rejected.title': '选拔结果公告',
    'status.rejected.desc': '抱歉，您在此次选拔中未成功。不要放弃！您可以在下一期再次尝试。',
    'status.rejected.view.feedback': '查看反馈',
    'status.rejected.registration.info': '注册信息',
    
    // Notifikasi
    'notification.toefl.warning': 'TOEFL文件不符合要求，请重新上传',
    'notification.payment.verified': '您的付款已通过验证',
    'notification.time.2hours': '2小时前',
    'notification.time.1day': '1天前',
    
    // Quick Actions
    'quick.upload.documents': '上传文件',
    'quick.view.announcement': '查看公告',
    'quick.download.guide': '下载指南',
    
    // Login Page
    'login.title': '管理学博士项目注册',
    'login.description': '加入STIE Mahardhika Surabaya管理学博士项目，通过国际标准化课程和经验丰富的讲师发展您的管理专业知识。',
    'login.accreditation': '优秀认证和全球学术网络',
    'login.signin.title': '登录',
    'login.signin.subtitle': '输入您的凭据以访问您的账户',
    'login.email.label': '电子邮件地址',
    'login.email.placeholder': 'you@example.com',
    'login.password.label': '密码',
    'login.password.placeholder': '••••••••',
    'login.remember': '记住我',
    'login.forgot': '忘记密码？',
    'login.signin.button': '登录',
    'login.no.account': '没有账户？',
    'login.create.account': '立即创建',
    
    // Curriculum Page
    'curriculum.title': '课程结构',
    'curriculum.subtitle': 'STIE Mahardhika 管理学博士项目',
    'curriculum.description': '课程设计全面，旨在培养高质量的研究人员和学者',
    'curriculum.total.sks': '总学分',
    'curriculum.concentrations': '专业方向',
    'curriculum.semesters': '学期',
    'curriculum.matriculation.sks': '预科学分',
    'curriculum.matriculation.title': '预科课程',
    'curriculum.matriculation.subtitle': '学生水平提升项目',
    'curriculum.matriculation.info.title': '预科信息',
    'curriculum.matriculation.info.1': '预科课程是为学术背景与管理学不直接相关的学生提供的水平提升项目',
    'curriculum.matriculation.info.2': '在主要博士项目课程之外进行',
    'curriculum.matriculation.info.3': '旨在在开始博士项目前调整学生的基础知识',
    'curriculum.core.title': '核心课程',
    'curriculum.core.subtitle': '所有学生的基础课程',
    'curriculum.concentration.title': '专业方向课程',
    'curriculum.concentration.subtitle': '从两个可用的专业方向中选择一个。每个专业方向包含9个学分，必须根据所选专业领域完整修读。',
    'curriculum.concentration.info': '学生必须选择并完整完成一个专业方向（9个学分）',
    'curriculum.dissertation.title': '论文要求',
    'curriculum.dissertation.1': '论文提案资格（第三学期）- 3个学分',
    'curriculum.dissertation.2': '论文研究（含提案和可行性考试）（第四学期）- 9个学分',
    'curriculum.dissertation.3': '国际发表（第五学期）- 9个学分',
    'curriculum.dissertation.4': '论文（含闭卷和开卷考试）（第六学期）- 9个学分',
    'curriculum.summary.title': '学习负担总结',
    'curriculum.summary.core': '核心学分',
    'curriculum.summary.concentration': '专业方向学分',
    'curriculum.summary.matriculation': '预科学分',
    'curriculum.summary.total': '总学分',
    'curriculum.summary.core.desc': '第一至六学期',
    'curriculum.summary.concentration.desc': '一个选定专业方向',
    'curriculum.summary.matriculation.desc': '项目外',
    'curriculum.summary.total.desc': '完整项目',
    'curriculum.roadmap.title': '学术路线图',
    'curriculum.roadmap.year1': '第一年',
    'curriculum.roadmap.year2': '第二年',
    'curriculum.roadmap.year3': '第三年',
    'curriculum.roadmap.year1.desc': '第一至二学期',
    'curriculum.roadmap.year2.desc': '第三至四学期',
    'curriculum.roadmap.year3.desc': '第五至六学期',
    'curriculum.roadmap.year1.1': '核心课程（科学哲学、研究方法、高级管理理论）',
    'curriculum.roadmap.year1.2': '选修专业方向课程（人力资源管理或市场营销）',
    'curriculum.roadmap.year1.3': '确定论文研究主题',
    'curriculum.roadmap.year1.4': '准备论文提案',
    'curriculum.roadmap.year2.1': '论文提案资格（第三学期）',
    'curriculum.roadmap.year2.2': '论文研究（含提案考试）',
    'curriculum.roadmap.year2.3': '研究成果可行性考试',
    'curriculum.roadmap.year2.4': '完成研究阶段',
    'curriculum.roadmap.year3.1': '国际发表（第五学期）',
    'curriculum.roadmap.year3.2': '完成论文写作',
    'curriculum.roadmap.year3.3': '论文闭卷考试（第六学期）',
    'curriculum.roadmap.year3.4': '开卷考试和毕业',
    'curriculum.advantages.title': '项目优势',
    'curriculum.advantages.1': '具有国际发表记录的经验丰富的导师',
    'curriculum.advantages.2': '以研究为基础的课程，强调科学发表',
    'curriculum.advantages.3': '完整的研究设施，包括访问国际期刊数据库',
    'curriculum.advantages.4': '与领先大学和研究机构的研究合作',
    'curriculum.advantages.5': '国际会议和发表的资金支持',
    'curriculum.career.title': '毕业生职业前景',
    'curriculum.career.1': '大学学者和研究人员',
    'curriculum.career.2': '高级管理和商业顾问',
    'curriculum.career.3': '高管和组织领导者',
    'curriculum.career.4': '政府机构政策分析师',
    'curriculum.career.5': '研究机构和智库研究人员',
    'curriculum.cta.title': '准备开始您的学术之旅？',
    'curriculum.cta.description': '加入管理学博士项目，发展您的研究潜力，为学术界和管理实践做出真正贡献',
    'curriculum.cta.register': '立即注册',
    'curriculum.cta.brochure': '下载手册',
    
    // Modal Registration
    'modal.registration.title': '在线注册',
    'modal.registration.step': '步骤',
    'modal.registration.of': '共',
    'modal.registration.personal.info': '个人信息',
    'modal.registration.academic.info': '学术信息',
    'modal.registration.fullname.placeholder': '姓名',
    'modal.registration.email.placeholder': '邮箱',
    'modal.registration.phone.placeholder': '电话号码 (10-13位)',
    'modal.registration.ktp.placeholder': '身份证号 (16位)',
    'modal.registration.upload.photo': '上传照片',
    'modal.registration.search.s1': '搜索本科大学',
    'modal.registration.search.s2': '搜索硕士大学',
    'modal.registration.gpa.s1.placeholder': '本科GPA (0-4)',
    'modal.registration.gpa.s2.placeholder': '硕士GPA (0-4)',
    'modal.registration.loading.universities': '正在加载大学...',
    'modal.registration.file.selected': '已选择文件：',
    'modal.registration.back': '返回',
    'modal.registration.next': '下一步',
    'modal.registration.submit': '注册',
    'modal.registration.success': '表单提交成功！',
    'modal.registration.error.api': '加载大学数据失败',
    
    // Validation Messages
    'validation.fullname.required': '姓名是必填项',
    'validation.email.required': '邮箱是必填项',
    'validation.email.invalid': '邮箱格式无效',
    'validation.phone.required': '电话号码是必填项',
    'validation.phone.invalid': '电话号码必须是10-13位',
    'validation.ktp.required': '身份证号是必填项',
    'validation.ktp.invalid': '身份证号必须是16位',
    'validation.photo.required': '必须上传照片',
    'validation.s1.university.required': '本科大学是必填项',
    'validation.s1.gpa.required': '本科GPA是必填项',
    'validation.s1.gpa.invalid': 'GPA必须在0-4之间',
    'validation.s2.university.required': '硕士大学是必填项',
    'validation.s2.gpa.required': '硕士GPA是必填项',
    'validation.s2.gpa.invalid': 'GPA必须在0-4之间',
    'curriculum.info.flexible': '灵活时间表',
    'curriculum.info.flexible.desc': '为在职专业人士设计的周末和高管班课程',
    'curriculum.info.accreditation': '认证',
    'curriculum.info.accreditation.desc': '符合印尼国家高等教育标准的认证项目',
    'curriculum.info.publication': '科学发表',
    'curriculum.info.publication.desc': '鼓励学生在国家和国际知名期刊发表文章',
    'curriculum.duration.normal': '年',
    'curriculum.duration.normal.desc': '正常学制',
    'curriculum.duration.max': '年',
    'curriculum.duration.max.desc': '最长学制',
    'curriculum.ratio': '师生比例',
    'curriculum.table.no': '序号',
    'curriculum.table.code': '课程代码',
    'curriculum.table.name': '课程名称',
    'curriculum.table.sks': '学分',
    'curriculum.table.semester': '学期',
    'curriculum.table.type': '类型',
    'curriculum.table.total': '总学分',
    'curriculum.type.required': '必修',
    'curriculum.type.concentration': '专业方向',
    'curriculum.type.matriculation': '预科',
    
    // Course Names
    'curriculum.course.economic.theory': '经济理论',
    'curriculum.course.management.theory': '管理理论',
    'curriculum.course.advanced.statistics': '高级统计学',
    'curriculum.course.philosophy.science': '科学哲学',
    'curriculum.course.research.methods': '研究方法',
    'curriculum.course.advanced.management': '高级管理理论',
    'curriculum.course.dissertation.qualification': '论文提案资格',
    'curriculum.course.dissertation.research': '论文研究',
    'curriculum.course.international.publication': '国际发表',
    'curriculum.course.dissertation': '论文',
    'curriculum.course.hrm': '人力资源管理',
    'curriculum.course.human.capital': '人力资本战略与发展',
    'curriculum.course.hrm.leadership': '领导力中的人力资源管理',
    'curriculum.course.marketing': '营销管理',
    'curriculum.course.marketing.strategy': '营销策略',
    'curriculum.course.consumer.behavior': '消费者行为理论',
    
    // Concentration Names
    'curriculum.concentration.hrm': '人力资源管理',
    'curriculum.concentration.marketing': '营销管理',
  }
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('id');

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['id', 'en', 'zh'].includes(savedLanguage)) {
      setLanguageState(savedLanguage);
    }
  }, []);

  // Save language to localStorage when it changes
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  // Translation function
  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
